# Generated by Django 4.2.16 on 2024-11-05 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=75)),
                ("priority", models.IntegerField(default=0)),
                ("planned_start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                ("activity_description", models.TextField()),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "activity",
            },
        ),
        migrations.CreateModel(
            name="ClientPartner",
            fields=[
                (
                    "client_name",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(max_length=75)),
                ("email", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "clientpartner",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(default="DEFAULT", max_length=20)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="React",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="default_user", max_length=100)),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_name",
                    models.CharField(max_length=75, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "team_name",
                    models.CharField(max_length=75, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "username",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                ("project_manager", models.BooleanField(default=False)),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "useraccount",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "role_name",
                    models.ForeignKey(
                        default="DEFAULT",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.role",
                    ),
                ),
                (
                    "team_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.team"
                    ),
                ),
            ],
            options={
                "db_table": "team_member",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=75)),
                ("priority", models.IntegerField(default=0)),
                ("planned_start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                ("task_description", models.TextField()),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "actual_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.activity"
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=75)),
                ("planned_start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                (
                    "planned_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "spent_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("description", models.TextField()),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"project_manager": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="PrecedingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preceding_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preceding_tasks",
                        to="app.task",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsequent_tasks",
                        to="app.task",
                    ),
                ),
            ],
            options={
                "db_table": "precedingtask",
            },
        ),
        migrations.CreateModel(
            name="PrecedingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsequent_activities",
                        to="app.activity",
                    ),
                ),
                (
                    "preceding_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preceding_activities",
                        to="app.activity",
                    ),
                ),
            ],
            options={
                "db_table": "precedingactivity",
            },
        ),
        migrations.CreateModel(
            name="OnProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("is_client", models.BooleanField()),
                ("is_partner", models.BooleanField()),
                ("description", models.TextField()),
                (
                    "client_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.clientpartner",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.project"
                    ),
                ),
            ],
            options={
                "db_table": "on_project",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="user_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.useraccount"
            ),
        ),
        migrations.CreateModel(
            name="Assigned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.activity"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "role_name",
                    models.ForeignKey(
                        default="DEFAULT",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.role",
                    ),
                ),
            ],
            options={
                "db_table": "assigned",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
    ]
